import os

print("AZURE_OPENAI_API_KEY:", os.getenv("AZURE_OPENAI_API_KEY"))
print("AZURE_OPENAI_DEPLOYMENT_GPT_4O_MINI:", os.getenv("AZURE_OPENAI_DEPLOYMENT_GPT_4O_MINI"))
print("OPENAI_MODEL_GPT_4O_MINI:", os.getenv("OPENAI_MODEL_GPT_4O_MINI"))